
package com.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculatorImpl", targetNamespace = "http://test.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculatorImpl {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://test.com/", className = "com.test.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://test.com/", className = "com.test.AddResponse")
    @Action(input = "http://test.com/CalculatorImpl/addRequest", output = "http://test.com/CalculatorImpl/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "subtract", targetNamespace = "http://test.com/", className = "com.test.Subtract")
    @ResponseWrapper(localName = "subtractResponse", targetNamespace = "http://test.com/", className = "com.test.SubtractResponse")
    @Action(input = "http://test.com/CalculatorImpl/subtractRequest", output = "http://test.com/CalculatorImpl/subtractResponse")
    public float subtract(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        float arg1);

}
