
package com.endpoint;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConvertorImplService", targetNamespace = "http://endpoint.com/", wsdlLocation = "http://localhost:8080/WS/Convertor?wsdl")
public class ConvertorImplService
    extends Service
{

    private final static URL CONVERTORIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONVERTORIMPLSERVICE_EXCEPTION;
    private final static QName CONVERTORIMPLSERVICE_QNAME = new QName("http://endpoint.com/", "ConvertorImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/WS/Convertor?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONVERTORIMPLSERVICE_WSDL_LOCATION = url;
        CONVERTORIMPLSERVICE_EXCEPTION = e;
    }

    public ConvertorImplService() {
        super(__getWsdlLocation(), CONVERTORIMPLSERVICE_QNAME);
    }

    public ConvertorImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONVERTORIMPLSERVICE_QNAME, features);
    }

    public ConvertorImplService(URL wsdlLocation) {
        super(wsdlLocation, CONVERTORIMPLSERVICE_QNAME);
    }

    public ConvertorImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONVERTORIMPLSERVICE_QNAME, features);
    }

    public ConvertorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConvertorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConvertorImpl
     */
    @WebEndpoint(name = "ConvertorImplPort")
    public ConvertorImpl getConvertorImplPort() {
        return super.getPort(new QName("http://endpoint.com/", "ConvertorImplPort"), ConvertorImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConvertorImpl
     */
    @WebEndpoint(name = "ConvertorImplPort")
    public ConvertorImpl getConvertorImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.com/", "ConvertorImplPort"), ConvertorImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONVERTORIMPLSERVICE_EXCEPTION!= null) {
            throw CONVERTORIMPLSERVICE_EXCEPTION;
        }
        return CONVERTORIMPLSERVICE_WSDL_LOCATION;
    }

}
