
package com.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConvertorImpl", targetNamespace = "http://endpoint.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConvertorImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "dollarToRupee", targetNamespace = "http://endpoint.com/", className = "com.endpoint.DollarToRupee")
    @ResponseWrapper(localName = "dollarToRupeeResponse", targetNamespace = "http://endpoint.com/", className = "com.endpoint.DollarToRupeeResponse")
    @Action(input = "http://endpoint.com/ConvertorImpl/dollarToRupeeRequest", output = "http://endpoint.com/ConvertorImpl/dollarToRupeeResponse")
    public int dollarToRupee(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
