//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.03.18 at 04:23:18 PM IST 
//


package com.test;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.example.org/Calc}AddRequest"/>
 *         &lt;element ref="{http://www.example.org/Calc}AddResponse"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "addRequest",
    "addResponse"
})
@XmlRootElement(name = "calculator")
public class Calculator {

    @XmlElement(name = "AddRequest", required = true)
    protected AddRequest addRequest;
    @XmlElement(name = "AddResponse", required = true)
    protected AddResponse addResponse;

    /**
     * Gets the value of the addRequest property.
     * 
     * @return
     *     possible object is
     *     {@link AddRequest }
     *     
     */
    public AddRequest getAddRequest() {
        return addRequest;
    }

    /**
     * Sets the value of the addRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddRequest }
     *     
     */
    public void setAddRequest(AddRequest value) {
        this.addRequest = value;
    }

    /**
     * Gets the value of the addResponse property.
     * 
     * @return
     *     possible object is
     *     {@link AddResponse }
     *     
     */
    public AddResponse getAddResponse() {
        return addResponse;
    }

    /**
     * Sets the value of the addResponse property.
     * 
     * @param value
     *     allowed object is
     *     {@link AddResponse }
     *     
     */
    public void setAddResponse(AddResponse value) {
        this.addResponse = value;
    }

}
